### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by nurgasemetey** [Paraboly/pwc-tooltip#2]
Hello,

Nice work. Could you add demo?

**Comment by kuraydev** [comment]
Demo is already included in all StencilJS libraries. 
## How to?
* Simply clone the project
* Run the command on terminal:
`npm i`
* Run the command to start the demo: 
`npm start`

**Comment by kuraydev** [comment]
The demo is included with CodePen now :) @nurgasemetey 

[Codepen Example](https://github.com/Paraboly/pwc-tooltip/blob/master/README.md#live-codepen-example)
